version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: working-time-mysql
    environment:
      PASSWORD: root
      DATABASE: task_management
      USERNAME: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  working-time-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_TESTS: "true"
    container_name: working-time-app
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:mysql://mysql:3306/task_management
      - USERNAME=root
      - PASSWORD=root
      - JWT_SECRET=myVerySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: